# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-26 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='producto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='saldo_general',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
