# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-27 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to=b'imagenes'),
        ),
    ]
